--BUTCHERS
--CHICKEN
INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_TITLE, CATEGORY, DESCRIPTION, PRICE, QUANTITY, IMAGE) VALUES (1, 'CHICKEN', 'WHITE MEAT','CHICKEN IS THE MOST COMMON TYPE OF POULTRY. CHICKEN MEAT AND EGGS HAVE BECOME COMMON IN MANY CUISINES DUE TO THE RELATIVE EASE AND LOW COST OF KEEPING CHICKENS COMPARED TO MAMMALS SUCH AS CATTLE OR HOGS', '2.46', '15' , 'chicken.jpg');

--TURKEY
INSERT INTO PRODUCT(PRODUCT_ID, PRODUCT_TITLE, CATEGORY, DESCRIPTION, PRICE, QUANTITY, IMAGE) VALUES('2','TURKEY','WHITE MEAT','TURKEY IS A LARGE POULTRY BIRD THAT IS SIMILAR TO CHICKEN IN THE WHITE MEAT CATEGORY. TURKEY MEAT SEEMS TO BE LITTLE DARKER THAN CHICKEN MEAT, BUT WITH FEWER CALORIES. MANY OF THE HEALTH BENEFITS OF TURKEY MEAT ARE SIMILAR TO CHICKEN. LEAN PROTEIN CAN BE FOUND IN TURKEY BREAST, DRUMSTICK, AND WINGS. TURKEY IS ALSO RELATIVELY CHEAP, SO IT IS A NUTRIENT-DENSE FOOD WITH A LOW COST.','4','35','turkey.jpg');

--DUCK
INSERT INTO PRODUCT(PRODUCT_ID, PRODUCT_TITLE, CATEGORY, DESCRIPTION, PRICE, QUANTITY, IMAGE) VALUES('3','DUCK','WHITE MEAT','DUCK IS ANOTHER BIRD IS ANOTHER WHITE MEAT CATEGORY,. DUCK MEAT IS DARKER THAN CHICKEN OR TURKEY, BUT IT IS STILL CONSIDERED AS WHITE MEAT. DUCKS ARE A HEALTHY MEAT TO CONSUME BECAUSE THEY ARE NUTRIENT-DENSE. ANTIOXIDANTS CAN ALSO BE FOUND IN COOKED DUCK. ONE STUDY FOUND THAT ROASTED DUCK MEAT HAS MORE ANTIOXIDANTS THAN UNCOOKED DUCK MEAT','2.64','10','duck.jpg');

--PORK
INSERT INTO PRODUCT(PRODUCT_ID, PRODUCT_TITLE, CATEGORY, DESCRIPTION, PRICE, QUANTITY, IMAGE) VALUES('4','PORK','RED MEAT','PORK IS CLASSIFIED AS RED MEAT DUE TO MYOGLOBIN LEVELS IN THE MEAT. EVEN THOUGH FRESH PORK IS LIGHTER IN COLOR THAN BEEF AND COOKS TO BECOME VERY LIGHT.','2.64','17','pork.jpg');

--BEEF
INSERT INTO PRODUCT(PRODUCT_ID, PRODUCT_TITLE, CATEGORY, DESCRIPTION, PRICE, QUANTITY, IMAGE) VALUES('5','BEEF','RED MEAT','BEEF IS THE MOST COMMONLY CONSUMED RED MEAT. BEEF CHUNKS ARE GOOD IN STEWS, GROUND BEEF IS MADE INTO HAMBURGERS, AND DIFFERENT CUTS OF BEEF ARE USED FOR VARIOUS TYPES OF STEAK. BEEF CONTAINS MANY PROTEINS AND NUTRIENTS. IN FACT, IT IS ONE OF THE BEST DIETARY IRON SOURCES AVAILABLE.', '14.16','25','beef.jpg');

--LAMB
INSERT INTO PRODUCT(PRODUCT_ID, PRODUCT_TITLE, CATEGORY, DESCRIPTION, PRICE, QUANTITY, IMAGE) VALUES('6','LAMB','RED MEAT','LAMB IS THE MEAT OF YOUNG DOMESTIC SHEEP. IT IS A FORM OF RED MEAT, WHICH IS DEFINED AS MEAT FROM ANIMALS THAT HAS MORE IRON THAN POULTRY OR FISH. LAMB REFERS TO THE FLESH OF YOUNG SHEEP IN THEIR FIRST YEAR, WHEREAS MUTTON REFERS TO THE MEAT OF ADULT SHEEP.', '6.50','19','lamb.jpg');

--GREENGROCHER
--VEGETABLE
--POTATO
INSERT INTO PRODUCT(PRODUCT_ID, PRODUCT_TITLE, CATEGORY, DESCRIPTION, PRICE, QUANTITY, IMAGE) VALUES('7','POTATO','VEGETABLE','POTATOES ARE QUITE ROUND VEGETABLES WITH BROWN OR RED SKINS AND WHITE INSIDES.POTATOES ARE AN EXCELLENT SOURCE OF VITAMIN C, POTASSIUM, FIBRE, B VITAMINS COPPER, TRYPTOPHAN, MANGANESE AND EVEN LUTEIN, NOTES THE BOOK "HEALING FOODS" BY DK PUBLISHING. IT ALSO WORKS WONDERS FOR CURBING INFLAMMATION IN THE BODY AND BOOST IMMUNITY AND HEALTHY BLOOD CIRCULATION.', '0.97','100','potato.jpg');

--CAULIFLOWER
INSERT INTO PRODUCT(PRODUCT_ID, PRODUCT_TITLE, CATEGORY, DESCRIPTION, PRICE, QUANTITY, IMAGE) VALUES('8','CAULIFLOWER','VEGETABLE','CAULIFLOWER IS ONE OF SEVERAL VEGETABLES IN THE SPECIES BRASSICA OLERACEA IN THE GENUS BRASSICA, WHICH IS IN THE BRASSICACEAE (OR MUSTARD) FAMILY. IT IS AN ANNUAL PLANT THAT REPRODUCES BY SEED.CAULIFLOWER HEADS RESEMBLE THOSE IN BROCCOLI, WHICH DIFFERS IN HAVING FLOWER BUDS AS THE EDIBLE PORTION.CAULIFLOWER IS A CRUCIFEROUS VEGETABLE THAT IS NATURALLY HIGH IN FIBER AND B-VITAMINS.', '2','25','cauliflower.jpg');

--BROCCOLI
INSERT INTO PRODUCT(PRODUCT_ID, PRODUCT_TITLE, CATEGORY, DESCRIPTION, PRICE, QUANTITY, IMAGE) VALUES('9','BROCCOLI','VEGETABLE','BROCCOLI IS AN EDIBLE GREEN PLANT IN THE CABBAGE FAMILY.  IT CAN BE EATEN FRESH OR COOKED. VITAMIN C AND VITAMIN K ARE VERY ABUNDANT IN BROCCOLI. BROCCOLI IS A NUTRIENT-DENSE FOOD THAT CAN HELP YOU LIVE A HEALTHIER LIFE BY REDUCING INFLAMMATION, IMPROVING BLOOD SUGAR CONTROL, INCREASING IMMUNITY, AND ENCOURAGING HEART HEALTH.','1.5','20', 'broccolli.jpg');

--BRINJAL
INSERT INTO PRODUCT(PRODUCT_ID, PRODUCT_TITLE, CATEGORY, DESCRIPTION, PRICE, QUANTITY, IMAGE) VALUES('10','EGGPLANT','VEGETABLE','EGGPLANT IS A VEGETABLE THAT COMES IN A VARIETY OF SHAPES, SIZES, AND COLORS AND FLOURISHES IN HOT AREAS AND THROUGHOUT THE SUMMER MONTHS. THEY DIFFER IN SIZE FROM LITTLE GLOBES WITH A DIAMETER OF TWO INCHES TO MORE RECTANGULAR AND TUBULAR VARIETIES WITH A LENGTH OF 12 INCHES OR MORE. ALL EGGPLANT TYPES HAVE EDIBLE SEEDS, MAKING IT PARTICULARLY SIMPLE TO PREPARE.','1','20', 'eggplant.jpg');

--PUMPKIN
INSERT INTO PRODUCT(PRODUCT_ID, PRODUCT_TITLE, CATEGORY, DESCRIPTION, PRICE, QUANTITY, IMAGE) VALUES('11','PUMPKIN','VEGETABLE','A PUMPKIN IS A ROUND WINTER SQUASH CULTIVAR WITH SMOOTH, SLIGHTLY RIBBED SKIN THAT IS USUALLY DEEP YELLOW TO ORANGE IN COLOR. THE SEEDS AND PULP ARE CONTAINED WITHIN THE THICK SHELL. IT IS HIGHLY NUTRITIOUS AND PARTICULARLY RICH IN VITAMIN.', '0.15','90','pumpkin.jpg');

--TOMATO
INSERT INTO PRODUCT(PRODUCT_ID, PRODUCT_TITLE, CATEGORY, DESCRIPTION, PRICE, QUANTITY, IMAGE) VALUES('12','TOMATO','VEGETABLE','TOMATO IS A FLESHY BERRY, USUALLY OF RED COLOUR, ALTHOUGH THERE ARE ALSO PINK OR YELLOW TOMATOES.TOMATOES ARE THE MAJOR DIETARY SOURCE OF THE ANTIOXIDANT LYCOPENE, WHICH HAS BEEN LINKED TO MANY HEALTH BENEFITS, INCLUDING REDUCED RISK OF HEART DISEASE AND CANCER. THEY ARE ALSO A GREAT SOURCE OF VITAMIN C, POTASSIUM, FOLATE, AND VITAMIN K.', '2','25','tomato.jpg');

--CARROT
INSERT INTO PRODUCT(PRODUCT_ID, PRODUCT_TITLE, CATEGORY, DESCRIPTION, PRICE, QUANTITY, IMAGE) VALUES('13','CARROT','VEGETABLE','THE CARROT IS A ROOT VEGETABLE, USUALLY ORANGE IN COLOUR, THOUGH PURPLE, BLACK, RED, WHITE, AND YELLOW CULTIVARS EXIST.THE CARROT IS A BIENNIAL PLANT IN THE UMBELLIFER FAMILY APIACEAE. AT FIRST, IT GROWS A ROSETTE OF LEAVES WHILE BUILDING UP THE ENLARGED TAPROOT.CARROTS ARE A PARTICULARLY GOOD SOURCE OF BETA CAROTENE, FIBER, VITAMIN K1, POTASSIUM, AND ANTIOXIDANTS.','1.5','50','carrot.jpg');



--FRUITS
--ORANGE
INSERT INTO PRODUCT(PRODUCT_ID, PRODUCT_TITLE, CATEGORY, DESCRIPTION, PRICE, QUANTITY, IMAGE) VALUES('14','ORANGE','FRUIT','AN ORANGE HAS A TOUGH SHINY ORANGE SKIN. INSIDE, THE FRUIT IS DIVIDED INTO "SEGMENTS", WHICH HAVE THIN TOUGH SKINS THAT HOLD TOGETHER MANY LITTLE SECTIONS WITH JUICE INSIDE. IN SOME ORANGES IT IS HARD TO TAKE THE SKIN OFF. ORANGE SKIN IS OFTEN CALLED "ORANGE PEEL".ORANGES ARE A HEALTHY SOURCE OF FIBER, VITAMIN C, THIAMINE, FOLATE, AND ANTIOXIDANTS. THEY HAVE MULTIPLE HEALTH BENEFITS.','2','20', 'orange.jpg');

--APPLE
INSERT INTO PRODUCT(PRODUCT_ID, PRODUCT_TITLE, CATEGORY, DESCRIPTION, PRICE, QUANTITY, IMAGE) VALUES('15','APPLE','FRUIT','APPLES ARE THE IDEAL FRUIT TO EAT AT ANY TIME, HAVING A POSITIVE ROLE IN THE ACHIEVEMENT OF NOURISH BALANCE. THEIR SKIN MAY BE GREEN, YELLOW OR REDDISH, AND THE MEAT TASTE RANGES FROM A BITTER TO SWEET FLAVOUR.APPLES ARE A POPULAR FRUIT, CONTAINING ANTIOXIDANTS, VITAMINS, DIETARY FIBER, AND A RANGE OF OTHER NUTRIENTS. DUE TO THEIR VARIED NUTRIENT CONTENT, THEY MAY HELP PREVENT SEVERAL HEALTH CONDITIONS.','5','45','apple.jpg');

--PINEAPPLE
INSERT INTO PRODUCT(PRODUCT_ID, PRODUCT_TITLE, CATEGORY, DESCRIPTION, PRICE, QUANTITY, IMAGE) VALUES('16','PINEAPPLE','FRUIT','THE PINEAPPLE IS A TROPICAL FRUITING PLANT THAT IS THE MOST ECONOMICALLY IMPORTANT OF THE BROMELIACEAE FAMILY. THE PINEAPPLE IS NATIVE TO SOUTH AMERICA AND HAS BEEN GROWN THERE FOR GENERATIONS.  IT IS LOW IN CALORIES AND HIGH IN VITAMINS AND MINERALS. ONE CUP OF PINEAPPLE CHUNKS WILL DELIVER: VITAMIN C: YOU WILL GET ONE-THIRD OF YOUR DAILY VALUE OF VITAMIN C WHICH AIDS IN TISSUE GROWTH AND REPAIR.','2','20', 'pineapple.jpg');

--STARWBERRY
INSERT INTO PRODUCT(PRODUCT_ID, PRODUCT_TITLE, CATEGORY, DESCRIPTION, PRICE, QUANTITY, IMAGE) VALUES('17','STARWBERRY','FRUIT','THE STRAWBERRY IS A SUCCULENT AND FRAGRANT FRUIT WITH A BRIGHT RED COLOR THAT COMES FROM THE SAME PLANT. IT IS KNOWN AS THE QUEEN OF THE FRUIT IN THE WEST... THE STRAWBERRY IS A SUCCULENT AND FRAGRANT FRUIT WITH A BRIGHT RED COLOR THAT COMES FROM THE SAME PLANT. THESE POWERFUL LITTLE PACKAGES PROTECT YOUR HEART, INCREASE HDL (GOOD) CHOLESTEROL, REDUCE BLOOD PRESSURE, AND PROTECT YOU FROM CANCER.','2','20','strawberry.jpg');

--MANGO
INSERT INTO PRODUCT(PRODUCT_ID, PRODUCT_TITLE, CATEGORY, DESCRIPTION, PRICE, QUANTITY, IMAGE) VALUES('18','MANGO','FRUIT','MANGOES ARE SWEET, CREAMY FRUITS THAT HAVE A RANGE OF POSSIBLE HEALTH BENEFITS. THEY ARE HIGHLY POPULAR AROUND THE WORLD. THEY ARE A GREAT SOURCE OF MAGNESIUM AND POTASSIUM, BOTH OF WHICH ARE CONNECTED TO LOWER BLOOD PRESSURE AND A REGULAR PULSE. FURTHERMORE, MANGOS ARE THE SOURCE OF A COMPOUND KNOWN AS MANGIFERIN, WHICH EARLY STUDIES SUGGEST MAY BE ABLE TO REDUCE INFLAMMATION OF THE HEART.','2','40', 'mango.jpg');

--BANANA
INSERT INTO PRODUCT(PRODUCT_ID, PRODUCT_TITLE, CATEGORY, DESCRIPTION, PRICE, QUANTITY, IMAGE) VALUES('19','BANANA','FRUIT','A BANANA IS AN ELONGATED, EDIBLE FRUIT – BOTANICALLY A BERRY – PRODUCED BY SEVERAL KINDS OF LARGE HERBACEOUS FLOWERING PLANTS IN THE GENUS MUSA. IN SOME COUNTRIES, BANANAS USED FOR COOKING MAY BE CALLED "PLANTAINS", DISTINGUISHING THEM FROM DESSERT BANANAS.BANANAS ARE A GOOD SOURCE OF POTASSIUM. A DIET HIGH IN POTASSIUM CAN LOWER BLOOD PRESSURE IN PEOPLE WITH ELEVATED LEVELS.','1','40','banana.jpg');

--AVOCADO
INSERT INTO PRODUCT(PRODUCT_ID, PRODUCT_TITLE, CATEGORY, DESCRIPTION, PRICE, QUANTITY, IMAGE) VALUES('20','AVOCADO','FRUIT','THE AVOCADO IS A TREE ORIGINATING IN THE AMERICAS WHICH IS LIKELY NATIVE TO THE HIGHLAND REGIONS OF SOUTH-CENTRAL MEXICO TO GUATEMALA. IT IS CLASSIFIED AS A MEMBER OF THE FLOWERING PLANT FAMILY LAURACEAE. THE FRUIT OF THE PLANT, ALSO CALLED AN AVOCADO, IS BOTANICALLY A LARGE BERRY CONTAINING A SINGLE LARGE SEED.','2.94','40','avocado.jpg');

--FISHMONGER
--SALMON
INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_TITLE, CATEGORY, DESCRIPTION, PRICE, QUANTITY, IMAGE) VALUES ('21', 'SALMON', 'FISH','SALMON IS THE COMMON NAME FOR SEVERAL SPECIES OF RAY-FINNED FISH IN THE FAMILY SALMONIDAE. SALMON IS A RICH SOURCE OF OMEGA-3 FATTY ACIDS (EPA AND DHA) AND POTASSIUM. THE OMEGA-3 AND -6 FATTY ACIDS COMBINED WITH POTASSIUM GREATLY CONTRIBUTE TO HEART HEALTH, AS THEY REDUCE ARTERY INFLAMMATION, LOWER CHOLESTEROL LEVELS, AND MAINTAIN BLOOD PRESSURE LEVELS.', '4.5', '35' , 'salmon.jpg');

--TUNA
INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_TITLE, CATEGORY, DESCRIPTION, PRICE, QUANTITY, IMAGE) VALUES ('22', 'TUNA', 'FISH','TUNA IS A SALTWATER FISH EATEN ALL OVER THE WORLD. IT IS INCREDIBLY NUTRITIOUS AND A GREAT SOURCE OF PROTEIN, OMEGA-3 FATTY ACIDS.', '3.5', '5' , 'tuna.jpg');

--CRAB
INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_TITLE, CATEGORY, DESCRIPTION, PRICE, QUANTITY, IMAGE) VALUES ('23', 'CRAB', 'SHELLFISH','CRABMEAT IS THE MEAT FOUND WITHIN A CRAB. IT IS USED IN MANY CUISINES ACROSS THE WORLD, PRIZED FOR ITS SOFT, DELICATE AND SWEET TASTE.RICH IN VITAMINS AND MINERALS, CRAB IS ALSO LOW IN FAT AND CONTAINS OMEGA-3 POLYUNSATURATED ACIDS. HELPS PROVIDE PROTECTION FROM HEART DISEASE AND AIDS BRAIN DEVELOPMENT.','9', '25' , 'crab.jpg');

--OCTOPUS
INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_TITLE, CATEGORY, DESCRIPTION, PRICE, QUANTITY, IMAGE) VALUES ('24', 'OCTOPUS', 'SHELLFISH','OCTOPUS IS AN EXCELLENT SOURCE OF OMEGA-3 FATTY ACIDS, "GOOD FATS" LINKED TO A RANGE OF HEART-HEALTHY BENEFITS. OMEGA-3S CAN LOWER YOUR BLOOD PRESSURE AND SLOW THE BUILDUP OF PLAQUE IN YOUR ARTERIES, REDUCING STRESS ON THE HEART.', '10','5', 'octopus.jpg');

--TROUT
INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_TITLE, CATEGORY, DESCRIPTION, PRICE, QUANTITY, IMAGE) VALUES ('25', 'TROUT', 'FISH','TROUT AND OTHER SALMONIDS CAN EFFICIENTLY DIGEST FOODS THAT CONTAIN PRIMARILY PROTEIN (MOSTLY FROM FISH), AND CAN OBTAIN SOME OF THEIR ENERGY FROM FATS AND, TO A LESSER EXTENT, FROM CARBOHYDRATES. FRY AND FINGERLING TROUT REQUIRE A HIGHER PROTEIN AND ENERGY CONTENT IN THEIR DIETS THAN LARGER FISH.', '3.5', '20' , 'trout.jpg');

--LOBSTER
INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_TITLE, CATEGORY, DESCRIPTION, PRICE, QUANTITY, IMAGE) VALUES ('26', 'LOBSTER', 'SHELLFISH','THE KING OF THE CRUSTACEANS, LOBSTER IS A DELICACY THAT COMMANDS A VERY HIGH PRICE, WITH WHITE, FIRM MEAT THAT IS SWEET AND SUCCULENT.BEFORE IT IS COOKED, LOBSTER SHELL HAS A VERY DARK COLOUR, WITH TINTS THAT RANGE FROM BLUE/GREEN TO RED/PURPLE, IT GAINS ITS DISTINCTIVE DEEP RED BRICK COLOUR ONLY WHEN IT IS COOKED.LOBSTERS ARE A GREAT SOURCE OF SELENIUM AND ALSO CONTAIN OMEGA-3 FATTY ACIDS. THEY CAN HELP PROTECT AGAINST THYROID DISEASE, DEPRESSION, AND ANEMIA.', '3.46', '15' , 'lobster.jpg');

--SHRIMP
INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_TITLE, CATEGORY, DESCRIPTION, PRICE, QUANTITY, IMAGE) VALUES ('27', 'SHRIMP', 'SHELLFISH','SHRIMP MAY HAVE A VARIETY OF HEALTH BENEFITS. IT IS HIGH IN SEVERAL VITAMINS AND MINERALS, AND IS A RICH SOURCE OF PROTEIN. EATING SHRIMP MAY ALSO PROMOTE HEART AND BRAIN HEALTH DUE TO ITS CONTENT OF OMEGA-3 FATTY ACIDS AND THE ANTIOXIDANT ASTAXANTHIN.', '5', '25' , 'shrimp.jpg');

--PRAWN
INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_TITLE, CATEGORY, DESCRIPTION, PRICE, QUANTITY, IMAGE) VALUES ('28', 'PRAWN', 'SHELLFISH','PRAWN ARE IMPORTANT TYPES OF SEAFOOD THAT ARE CONSUMED WORLDWIDE. PRAWNS ARE A RICH SOURCE OF SELENIUM, ONE OF THE MOST EFFECTIVE ANTIOXIDANTS AT MAINTAINING HEALTHY CELLS. THEY ALSO CONTAIN HIGH LEVELS OF ZINC, WHICH IS IMPORTANT TO DEVELOP A HEALTHY IMMUNE SYSTEM. EATING PRAWNS HELPS BUILD STRONG BONES BECAUSE THEY CONTAIN PHOSPHOROUS, COPPER AND MAGNESIUM.','6', '15' , 'prawn.jpg');

--SCAMPI
INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_TITLE, CATEGORY, DESCRIPTION, PRICE, QUANTITY, IMAGE) VALUES ('29', 'SCAMPI', 'SHELLFISH','THE SHELLED TAIL MEAT IS GENERALLY REFERRED TO AS "SCAMPI TAILS" OR "WHOLETAIL SCAMPI", ALTHOUGH CHEAPER "RE-FORMED SCAMPI" CAN CONTAIN OTHER PARTS TOGETHER WITH OTHER FISH. IT IS SERVED FRIED IN BATTER OR BREADCRUMBS AND USUALLY WITH CHIPS AND TARTARE SAUCE.', '6.5', '10' , 'scampi.jpg');

--BAKERY
--BREAD
INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_TITLE, CATEGORY, DESCRIPTION, PRICE, QUANTITY, IMAGE) VALUES ('30', 'BREAD','BAKED ITEMS', 'BREAD IS A STAPLE FOOD PREPARED FROM A DOUGH OF FLOUR AND WATER, USUALLY BY BAKING.THE WHOLE GRAINS IN WHOLEMEAL BREAD HAVE MANY BENEFITS. THEY CAN BOOST OVERALL HEALTH AND HELP REDUCE THE RISK OF OBESITY AND VARIOUS OTHER COMPLICATIONS AND DISEASES.', '1.5','50', 'bread.jpg');

--BAGEL
INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_TITLE, CATEGORY, DESCRIPTION, PRICE, QUANTITY, IMAGE) VALUES ('31', 'BAGEL','BAKED ITEMS', 'A BAGEL (ALSO SPELLED BEIGEL) IS A TYPE OF BREAD, TRADITIONALLY SHAPED BY HAND INTO THE FORM OF A RING FROM WHEAT DOUGH, ROUGHLY HAND-SIZED. ... THE RESULT IS A DENSE, CHEWY, DOUGHY INTERIOR WITH A BROWNED AND SOMETIMES CRISP EXTERIOR, DEPENDING ON BAKE TYPE.BAGELS MADE FROM WHOLE GRAINS MAY HELP BALANCE BLOOD SUGAR, SUPPORT HEALTHY DIGESTION, AND PREVENT DISEASE.', '1','25', 'bagel.jpg');

--MUFFIN
INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_TITLE, CATEGORY, DESCRIPTION, PRICE, QUANTITY, IMAGE) VALUES ('32', 'MUFFIN','BAKED ITEMS', 'A MUFFIN IS AN INDIVIDUAL-SIZED, BAKED PRODUCT. IT CAN REFER TO TWO DISTINCT ITEMS, A PART-RAISED FLATBREAD THAT IS BAKED AND THEN COOKED ON A GRIDDLE AND A CUPCAKE-LIKE QUICKBREAD THAT IS CHEMICALLY LEAVENED AND THEN BAKED IN A MOLD.', '1','60', 'muffin.jpg');

--CAKE
INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_TITLE, CATEGORY, DESCRIPTION, PRICE, QUANTITY, IMAGE) VALUES ('33', 'CAKE', 'BAKED ITEMS','CAKE IS A FORM OF SWEET FOOD MADE FROM FLOUR, SUGAR, AND OTHER INGREDIENTS, THAT IS USUALLY BAKED. IN THEIR OLDEST FORMS, CAKES WERE MODIFICATIONS OF BREAD, BUT CAKES NOW COVER A WIDE RANGE OF PREPARATIONS.', '10','20', 'cake.jpg');

--PIZZA
INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_TITLE, CATEGORY, DESCRIPTION, PRICE, QUANTITY, IMAGE) VALUES ('34', 'PIZZA', 'BAKED ITEMS','PIZZA IS A SAVORY DISH OF ITALIAN ORIGIN CONSISTING OF A USUALLY ROUND, FLATTENED BASE OF LEAVENED WHEAT-BASED DOUGH TOPPED WITH TOMATOES, CHEESE, AND OFTEN VARIOUS OTHER INGREDIENTS WHICH IS THEN BAKED AT A HIGH TEMPERATURE, TRADITIONALLY IN A WOOD-FIRED OVEN.', '4','15', 'pizza.jpg');

--COOKIE
INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_TITLE, CATEGORY, DESCRIPTION, PRICE, QUANTITY, IMAGE) VALUES ('35', 'COOKIES','BAKED ITEMS', 'COOKIES ARE BROADLY CLASSIFIED ACCORDING TO HOW THEY ARE FORMED OR MADE, INCLUDING AT LEAST THESE CATEGORIES: BAR COOKIES CONSIST OF BATTER OR OTHER INGREDIENTS THAT ARE POURED OR PRESSED INTO A PAN (SOMETIMES IN MULTIPLE LAYERS) AND CUT INTO COOKIE-SIZED PIECES AFTER BAKING. ', '1.5','50', 'cookie.jpg');

--CROISSANT
INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_TITLE, CATEGORY, DESCRIPTION, PRICE, QUANTITY, IMAGE) VALUES ('36', 'CROISSANT','BAKED ITEMS', 'A CROISSANT IS A BUTTERY, CRESCENT-SHAPED FRENCH PASTRY. GOOD CROISSANTS ARE LIGHT, FLAKY, AND DELICATELY SWEET.COMPARED TO OTHER SWEETS, CROISSANT IS DISTINGUISHED BY THE CONTENT OF PROTEIN, VITAMIN B1 AND VITAMIN B9 (FOLIC ACID).', '3','20', 'croissant.jpg');

--PASTRY
INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_TITLE, CATEGORY, DESCRIPTION, PRICE, QUANTITY, IMAGE) VALUES ('37', 'PASTRY','BAKED ITEMS', 'PASTRY IS A DOUGH OF FLOUR, WATER AND SHORTENING THAT MAY BE SAVOURY OR SWEETENED. SWEETENED PASTRIES ARE OFTEN DESCRIBED AS BAKERS CONFECTIONERY. THE WORD "PASTRIES" SUGGESTS MANY KINDS OF BAKED PRODUCTS MADE FROM INGREDIENTS SUCH AS FLOUR, SUGAR, MILK, BUTTER, SHORTENING, BAKING POWDER, AND EGGS.', '5','10', 'pastry.jpg');

--Donut
INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_TITLE, CATEGORY, DESCRIPTION, PRICE, QUANTITY, IMAGE) VALUES ('38', 'DONUT','BAKED ITEMS', 'A doughnut or donut is a type of food made from leavened fried dough. It is popular in many countries and is prepared in various forms as a sweet snack that can be homemade or purchased in bakeries, supermarkets, food stalls, and franchised specialty vendors.', '0.5','50', 'donut.jpg');

--DELICATESSEN
--SANDWICH
INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_TITLE, CATEGORY, DESCRIPTION, PRICE, QUANTITY, IMAGE) VALUES ('39', 'SANDWICH','BAKED ITEMS', 'A SANDWICH IS A FOOD TYPICALLY CONSISTING OF VEGETABLES, SLICED CHEESE OR MEAT, PLACED ON OR BETWEEN SLICES OF BREAD, OR MORE GENERALLY ANY DISH WHEREIN BREAD SERVES AS A CONTAINER OR WRAPPER FOR ANOTHER FOOD TYPE.', '5','50', 'sandwich.jpg');

--SALAD
INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_TITLE, CATEGORY, DESCRIPTION, PRICE, QUANTITY, IMAGE) VALUES ('40', 'SALAD','BAKED ITEMS', 'A SALAD IS A DISH CONSISTING OF A MIXTURE OF SMALL PIECES OF FOOD, USUALLY VEGETABLES OR FRUIT. HOWEVER, DIFFERENT VARIETIES OF SALAD MAY CONTAIN VIRTUALLY ANY TYPE OF READY-TO-EAT FOOD.ANTIOXIDANTS AND OTHER NUTRIENTS IN SALAD VEGETABLES CAN BOOST YOUR HEALTH.','10', '20', 'salad.jpg');

--YOGURT
INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_TITLE, CATEGORY, DESCRIPTION, PRICE, QUANTITY, IMAGE) VALUES ('41', 'YOGURT','BAKED ITEMS', 'YOGURT IS A DAIRY PRODUCT MADE BY FERMENTING MILK WITH A YOGURT CULTURE. IT PROVIDES PROTEIN AND CALCIUM, AND IT MAY ENHANCE HEALTHY GUT BACTERIA.', '5','20', 'yogurt.jpg');

--COLD CUT MEAT
INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_TITLE, CATEGORY, DESCRIPTION, PRICE, QUANTITY, IMAGE) VALUES ('42', 'COLD CUT MEAT','BAKED ITEMS', 'COLD CUT MEATS ARE PRECOOKED OR CURED MEATS THAT ARE SLICED AND SERVED COLD OR HOT. THEY ARE TYPICALLY SERVED IN SANDWICHES OR ON A TRAY.', '7','20', 'coldcutmeat.jpg');

--CHEESE
INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_TITLE, CATEGORY, DESCRIPTION, PRICE, QUANTITY, IMAGE) VALUES ('43', 'CHEESE','BAKED ITEMS', 'CHEESE IS A DAIRY PRODUCT, DERIVED FROM MILK AND PRODUCED IN A WIDE RANGE OF FLAVORS, TEXTURES AND FORMS BY COAGULATION OF THE MILK PROTEIN CASEIN. IT COMPRISES PROTEINS AND FAT FROM MILK, USUALLY THE MILK OF COWS, BUFFALO, GOATS, OR SHEEP.', '3','20', 'cheese.jpg');

