DROP TRIGGER TRADER_ID;

--TRADER
CREATE OR REPLACE TRIGGER TRADER_ID
BEFORE INSERT ON TRADER
FOR EACH ROW
BEGIN
IF :NEW.TRADER_ID IS NULL THEN
select TRADER_ID_SEQ.nextval into :NEW.TRADER_ID from dual;
END IF;
END;
/

DROP  TRIGGER PRODUCT_ID;
--Product
CREATE OR REPLACE TRIGGER PRODUCT_ID
BEFORE INSERT ON PRODUCT
FOR EACH ROW
BEGIN
IF :NEW.PRODUCT_ID IS NULL THEN
select PRODUCT_ID_SEQ.nextval into :NEW.PRODUCT_ID from dual;
END IF;
END;
/

DROP TRIGGER CUST_ID;
--Customer
CREATE OR REPLACE TRIGGER CUST_ID
BEFORE INSERT ON CUSTOMER
FOR EACH ROW
BEGIN
IF :NEW.CUSTOMER_ID IS NULL THEN
select CUSTOMER_ID_SEQ.nextval into :NEW.CUSTOMER_ID from dual;
END IF;
END;
/

DROP TRIGGER REVIEW_ID;
--REVIEW 
CREATE OR REPLACE TRIGGER REVIEW_ID
BEFORE INSERT ON REVIEW
FOR EACH ROW 
BEGIN 
IF :NEW.REVIEW_ID IS NULL THEN 
select REVIEW_SEQUENCE.nextval into :NEW.REVIEW_ID from dual; 
END IF; 
END;
/